version=0.1

# default not used yet
[default.global.parameters]
[default.deploy.parameters]
[default.build.parameters]

# used for minor test deployments. like single policies before integration in template.yaml
[dev.deploy.parameters]
stack_name = 'CAST-test-delete-me'
s3_bucket = 'cost-reporting-vw'
region = 'eu-west-1'
capabilities = 'CAPABILITY_IAM'
parameter_overrides=[]
